# Generated by Django 3.2.1 on 2021-05-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_card', models.CharField(max_length=2)),
                ('second_card', models.CharField(max_length=2)),
                ('dealer_card', models.CharField(max_length=2)),
                ('time_hand', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(blank=True, max_length=10)),
                ('win_result', models.BooleanField(blank=True)),
            ],
        ),
    ]
