# Generated by Django 3.2.1 on 2021-05-25 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='decision',
        ),
        migrations.AddField(
            model_name='hand',
            name='played_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hand',
            name='dealer_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hand',
            name='first_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hand',
            name='second_card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hand',
            name='win_result',
            field=models.BooleanField(default=True),
        ),
    ]
