# Generated by Django 3.2.1 on 2021-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210526_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='decision',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
