# Generated by Django 3.2.1 on 2021-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_hand_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='decision',
            field=models.CharField(max_length=20),
        ),
    ]
