# Generated by Django 3.2.1 on 2021-05-31 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_alter_hand_win_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='played_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
